### ISSUE TITLE
Resource not closed

### ISSUE THREAD

**Issue by ash2k** [sajari/storage#2]
Hey, I was skimming through the sources and noticed that https://github.com/sajari/storage/blob/master/hash.go#L79 will return early without calling Close if copy fails. Just wanted to let you know.

p.s. thanks for the interesting talk yesterday at Golang Syd!

**Comment by dhowden** [comment]
Good spot - thanks for the report!

I have a lot of updates coming which will bring this package more in line with what I was talking about, so watch this space!
